<?php 

namespace App\Helpers;

class ReportFields {
    public static function getAvailableFields() {
        return [
            'Datos Personales' => [
                'nombre' => 'Nombre',
                'apellido' => 'Apellido',
                'sexo' => 'Sexo',
                'documento_de_identidad' => 'Documento de Identidad',
                'fecha_de_nacimiento' => 'Fecha de Nacimiento',
                'fecha_de_evaluacion' => 'Fecha de Evaluacion',
                'edad' => 'Edad',
                'grado' => 'Grado',
                'deporte' => 'Deporte',
                'categoria' => 'Categoria',
                'institucion' => 'Institución',
                'nombre_del_padre' => 'Nombre del Padre',
                'nombre_de_la_madre' => 'Nombre de la Madre',
                'nombre_tutor' => 'Nombre Tutor',
                'email_para_envio_de_reportes' => 'Email para envio de reportes',
                'numero_de_telefono' => 'Numero de Telefono',
            ],
            'Datos Antropometricos' => [
                'talla_parado' => 'Talla Parado',
                'talla_sentado' => 'Talla Sentado',
                'envergadura' => 'Envergadura',
                'peso' => 'Peso',
                'indice_cormico' => 'Indice Cormico',
                'phv' => 'PHV',
                'sumatoria_de_pliegues' => 'Sumatoria de Pliegues',
                'masa_adiposa_en_porcentaje' => 'Masa Adiposa en Porcentaje',
                'masa_adiposa_en_kg' => 'Masa Adiposa en Kg',
                'masa_muscular_en_porcentaje' => 'Masa Muscular en Porcentaje',
                'masa_muscular_en_kg' => 'Masa Muscular en Kg',
                'masa_residual_en_porcentaje' => 'Masa Residual en %',
                'masa_residual_en_kg' => 'Masa Residual en Kg',
                'masa_osea_en_porcentaje' => 'Masa Osea en %',
                'masa_osea_en_kg' => 'Masa Osea en Kg',
                'masa_de_la_piel_en_porcentaje' => 'Masa de la Piel en %',
                'masa_de_la_piel_en_kg' => 'Masa de la Piel en kg',
                'circunferencia_muslo_medio_derecha' => 'Circunferencia Muslo Medio Derecha',
                'circunferencia_muslo_medio_izquierda' => 'Circunferencia Muslo Medio Izquierda',
                'circunferencia_vasto_interno_derecha' => 'Circunferencia Vasto Interno Derecha',
                'circunferencia_vasto_interno_izquierda' => 'Circunferencia Vasto Interno Izquierda',
                'pliegue_anterior_muslo_derecho' => 'Pliegue Anterior Muslo Derecho',
                'pliegue_anterior_muslo_izquierdo' => 'Pliegue Anterior Muslo Izquierdo',
                'pliegue_posterior_muslo_derecho' => 'Pliegue Posterior Muslo Derecho',
                'pliegue_posterior_muslo_izquierdo' => 'Pliegue Posterior Muslo Izquierdo',
            ],
            'Lateralidad' => [
                'ojo' => 'Ojo',
                'hombro' => 'Hombro',
                'mano' => 'Mano',
                'cadera' => 'Cadera',
                'pie' => 'Pie',
            ],
            'Movilidad' => [
                'sit_and_reach' => 'Sit & Reach',
                'movilidad_tobillo_derecha' => 'Movilidad Tobillo - Derecha',
                'movilidad_tobillo_izquierda' => 'Movilidad Tobillo - Izquierda',
                'control_motor_anterior_derecha' => 'Control Motor Anterior - Derecha',
                'control_motor_anterior_izquierda' => 'Control Motor Anterior - Izquierda',
                'control_motor_postero_lateral_derecha' => 'Control Motor Postero Lateral - Derecha',
                'control_motor_postero_lateral_izquierda' => 'Control Motor Postero Lateral - Izquierda',
                'control_motor_postero_medial_derecha' => 'Control Motor Postero Medial - Derecha',
                'control_motor_postero_medial_izquierda' => 'Control Motor Postero Medial - Izquierda',
                'movilidad_de_hombro_derecha' => 'Movilidad de Hombro - Derecha',
                'movilidad_de_hombro_izquierda' => 'Movilidad de Hombro - Izquierda',
                'movilidad_toracica_derecha' => 'Movilidad Toracica - Derecha',
                'movilidad_toracica_izquierda' => 'Movilidad Toracica - Izquierda',
                'sentadilla_arranque' => 'Sentadilla Arranque',
                'paso_con_obstaculo_derecha' => 'Paso con Obstaculo Derecha',
                'paso_con_obstaculo_izquierda' => 'Paso con Obstaculo Izquierda',
                'desplante_en_linea_derecha' => 'Desplante en Linea Derecha',
                'desplante_en_linea_izquierda' => 'Desplante en Linea Izquierda',
                'elevacion_de_pierna_recta_derecha' => 'Elevacion de Pierna Recta Derecha',
                'elevacion_de_pierna_recta_izquierda' => 'Elevacion de Pierna Recta Izquierda',
                'estabilidad_de_tronco_en_extension' => 'Estabilidad de Tronco en Extension',
                'estabilidad_en_rotacion_derecha' => 'Estabilidad en Rotacion - Derecha',
                'estabilidad_en_rotacion_izquierda' => 'Estabilidad en Rotacion - Izquierda',
                'rotacion_de_cadera_interna_derecha' => 'Rotacion de Cadera Interna Derecha',
                'rotacion_de_cadera_interna_izquierda' => 'Rotacion de Cadera Interna Izquierda',
                'rotacion_de_cadera_externa_derecha' => 'Rotacion de Cadera Externa Derecha',
                'rotacion_de_cadera_externa_izquierda' => 'Rotacion de Cadera Externa Izquierda',
                'sit_and_reach_promedio_categoria' => 'Sit & Reach Promedio Categoria',
                'sit_and_reach_mas_alto_categoria' => 'Sit & Reach Mas Alto Categoria',
                'sit_and_reach_mme_mas_bajo_categoria' => 'Sit & Reach Mas Bajo Categoria',
            ],
            'Neuro Cognitivo Motor' => [
                'reaccion_oculo_manual' => 'Reaccion Oculo Manual',
                'reaccion_oculo_podal' => 'Reaccion Oculo Podal',
            ],
            'Fuerza' => [
                'agarre' => 'Agarre',
                'agarre_alto_categoria' => 'Agarre Alto Categoria',
                'agarre_promedio_categoria' => 'Agarre Promedio Categoria',
                'agarre_bajo_categoria' => 'Agarre Bajo Categoria',
            ],
            'Saltabilidad - Abalakov' => [
                'abalakov_altura_cm' => 'Altura cm',
                'abalakov_impulso' => 'Impulso',
                'abalakov_fuerza_maxima_propulsiva' => 'Fuerza Maxima Propulsiva',
                'abalakov_asimetria_propulsiva_der' => 'Asimetria Propulsiva Der',
                'abalakov_asimetria_propulsiva_izq' => 'Asimetria Propulsiva Izq',
                'abalakov_fuerza_maxima_frenado' => 'Fuerza Maxima Frenado',
                'abalakov_asimetria_frenado_der' => 'Asimetria Frenado Der',
                'abalakov_asimetria_frenado_izq' => 'Asimetria Frenado Izq',
                'abalakov_fuerza_maxima_aterrizaje' => 'Fuerza Maxima Aterrizaje',
                'abalakov_asimetria_aterrizaje_der' => 'Asimetria Aterrizaje Der',
                'abalakov_asimetria_aterrizaje_izq' => 'Asimetria Aterrizaje Izq',
                'abalakov_altura_promedio_categoria' => 'Altura Promedio Categoria',
                'abalakov_altura_alta_categoria' => 'Altura Alta Categoria',
                'abalakov_altura_baja_categoria' => 'Altura Baja Categoria',
                'abalakov_impulso_promedio_categoria' => 'Impulso Promedio Categoria',
                'abalakov_altura_desviacion_standar_categoria' => 'Altura Desviacion Standar Categoria',
                'abalakov_impulso_desviacion_standar_categoria' => 'Impulso Desviacion Standar Categoria',
                'abalakov_fuerza_maxima_propulsiva_categoria' => 'Fuerza Maxima Propulsiva Categoria',
            ],
            'Saltabilidad - CMJ' => [
                'cmj_altura_cm' => 'Altura cm',
                'cmj_impulso' => 'Impulso',
                'cmj_fuerza_maxima_propulsiva' => 'Fuerza Maxima Propulsiva',
                'cmj_asimetria_propulsiva_der' => 'Asimetria Propulsiva Der',
                'cmj_asimetria_propulsiva_izq' => 'Asimetria Propulsiva Izq',
                'cmj_fuerza_maxima_frenado' => 'Fuerza Maxima Frenado',
                'cmj_asimetria_frenado_der' => 'Asimetria Frenado Der',
                'cmj_asimetria_frenado_izq' => 'Asimetria Frenado Izq',
                'cmj_fuerza_maxima_aterrizaje' => 'Fuerza Maxima Aterrizaje',
                'cmj_asimetria_aterrizaje_der' => 'Asimetria Aterrizaje Der',
                'cmj_asimetria_aterrizaje_izq' => 'Asimetria Aterrizaje Izq',
                'cmj_altura_promedio_categoria' => 'Altura Promedio Categoria',
                'cmj_altura_alta_categoria' => 'Altura Alta Categoria',
                'cmj_altura_baja_categoria' => 'Altura Baja Categoria',
                'cmj_impulso_promedio_categoria' => 'Impulso Promedio Categoria',
                'cmj_altura_desviacion_standar_categoria' => 'Altura Desviacion Standar Categoria',
                'cmj_impulso_desviacion_standar_categoria' => 'Impulso Desviacion Standar Categoria',
                'cmj_fuerza_maxima_propulsiva_categoria' => 'Fuerza Maxima Propulsiva Categoria',
            ],
            'Saltabilidad - CMJ Unipodal Derecha' => [
                'cmj_unipodal_derecha_altura_cm' => 'Altura cm',
                'cmj_unipodal_derecha_impulso' => 'Impulso',
                'cmj_unipodal_derecha_fuerza_maxima_propulsiva' => 'Fuerza Maxima Propulsiva',
                'cmj_unipodal_derecha_fuerza_maxima_frenado' => 'Fuerza Maxima Frenado',
                'cmj_unipodal_derecha_fuerza_maxima_aterrizaje' => 'Fuerza Maxima Aterrizaje',
                'cmj_unipodal_derecha_altura_promedio_categoria' => 'Altura Promedio Categoria',
                'cmj_unipodal_derecha_altura_alta_categoria' => 'Altura Alta Categoria',
                'cmj_unipodal_derecha_altura_baja_categoria' => 'Altura Baja Categoria',
                'cmj_unipodal_derecha_impulso_promedio_categoria' => 'Impulso Promedio Categoria',
                'cmj_unipodal_derecha_altura_desviacion_standar_categoria' => 'Altura Desviacion Standar Categoria',
                'cmj_unipodal_derecha_impulso_desviacion_standar_categoria' => 'Impulso Desviacion Standar Categoria',
                'cmj_unipodal_derecha_fuerza_maxima_propulsiva_categoria' => 'Fuerza Maxima Propulsiva Categoria',
            ],
            'Saltabilidad - CMJ Unipodal Izquierda' => [
                'cmj_unipodal_izquierda_altura_cm' => 'Altura cm',
                'cmj_unipodal_izquierda_impulso' => 'Impulso',
                'cmj_unipodal_izquierda_fuerza_maxima_propulsiva' => 'Fuerza Maxima Propulsiva',
                'cmj_unipodal_izquierda_fuerza_maxima_frenado' => 'Fuerza Maxima Frenado',
                'cmj_unipodal_izquierda_fuerza_maxima_aterrizaje' => 'Fuerza Maxima Aterrizaje',
                'cmj_unipodal_izquierda_altura_promedio_categoria' => 'Altura Promedio Categoria',
                'cmj_unipodal_izquierda_altura_alta_categoria' => 'Altura Alta Categoria',
                'cmj_unipodal_izquierda_altura_baja_categoria' => 'Altura Baja Categoria',
                'cmj_unipodal_izquierda_impulso_promedio_categoria' => 'Impulso Promedio Categoria',
                'cmj_unipodal_izquierda_altura_desviacion_standar_categoria' => 'Altura Desviacion Standar Categoria',
                'cmj_unipodal_izquierda_impulso_desviacion_standar_categoria' => 'Impulso Desviacion Standar Categoria',
                'cmj_unipodal_izquierda_fuerza_maxima_propulsiva_categoria' => 'Fuerza Maxima Propulsiva Categoria',
            ],
            'Saltabilidad - Salto Profundo 30cm' => [
                'salto_profundo_30cm_rsi' => 'RSI',
                'salto_profundo_30cm_tiempo_de_piso' => 'Tiempo de Piso',
                'salto_profundo_30cm_tiempo_de_vuelo' => 'Tiempo de Vuelo',
                'salto_profundo_30cm_altura_cm' => 'Altura cm',
                'salto_profundo_30cm_impulso' => 'Impulso',
                'salto_profundo_30cm_fuerza_maxima_propulsiva' => 'Fuerza Maxima Propulsiva',
                'salto_profundo_30cm_asimetria_propulsiva_der' => 'Asimetria Propulsiva Der',
                'salto_profundo_30cm_asimetria_propulsiva_izq' => 'Asimetria Propulsiva Izq',
                'salto_profundo_30cm_fuerza_maxima_frenado' => 'Fuerza Maxima Frenado',
                'salto_profundo_30cm_asimetria_frenado_der' => 'Asimetria Frenado Der',
                'salto_profundo_30cm_asimetria_frenado_izq' => 'Asimetria Frenado Izq',
                'salto_profundo_30cm_fuerza_maxima_aterrizaje' => 'Fuerza Maxima Aterrizaje',
                'salto_profundo_30cm_asimetria_aterrizaje_der' => 'Asimetria Aterrizaje Der',
                'salto_profundo_30cm_asimetria_aterrizaje_izq' => 'Asimetria Aterrizaje Izq',
                'salto_profundo_30cm_rsi_categoria' => 'RSI Categoria',
                'salto_profundo_30cm_tiempo_de_piso_categoria' => 'Tiempo de Piso Categoria',
                'salto_profundo_30cm_altura_cm_categoria' => 'Altura cm Categoria',
                'salto_profundo_30cm_impulso_categoria' => 'Impulso Categoria',
                'salto_profundo_30cm_fuerza_maxima_propulsiva_categoria' => 'Fuerza Maxima Propulsiva Categoria',
                'salto_profundo_30cm_fuerza_maxima_frenado_categoria' => 'Fuerza Maxima Frenado Categoria',
                'salto_profundo_30cm_fuerza_maxima_aterrizaje_categoria' => 'Fuerza Maxima Aterrizaje Categoria',
            ],
            'Saltabilidad - Salto Profundo 45cm' => [
                'salto_profundo_45cm_rsi' => 'RSI',
                'salto_profundo_45cm_tiempo_de_piso' => 'Tiempo de Piso',
                'salto_profundo_45cm_tiempo_de_vuelo' => 'Tiempo de Vuelo',
                'salto_profundo_45cm_altura_cm' => 'Altura cm',
                'salto_profundo_45cm_impulso' => 'Impulso',
                'salto_profundo_45cm_fuerza_maxima_propulsiva' => 'Fuerza Maxima Propulsiva',
                'salto_profundo_45cm_asimetria_propulsiva_der' => 'Asimetria Propulsiva Der',
                'salto_profundo_45cm_asimetria_propulsiva_izq' => 'Asimetria Propulsiva Izq',
                'salto_profundo_45cm_fuerza_maxima_frenado' => 'Fuerza Maxima Frenado',
                'salto_profundo_45cm_asimetria_frenado_der' => 'Asimetria Frenado Der',
                'salto_profundo_45cm_asimetria_frenado_izq' => 'Asimetria Frenado Izq',
                'salto_profundo_45cm_fuerza_maxima_aterrizaje' => 'Fuerza Maxima Aterrizaje',
                'salto_profundo_45cm_asimetria_aterrizaje_der' => 'Asimetria Aterrizaje Der',
                'salto_profundo_45cm_asimetria_aterrizaje_izq' => 'Asimetria Aterrizaje Izq',
                'salto_profundo_45cm_rsi_categoria' => 'RSI Categoria',
                'salto_profundo_45cm_tiempo_de_piso_categoria' => 'Tiempo de Piso Categoria',
                'salto_profundo_45cm_altura_cm_categoria' => 'Altura cm Categoria',
                'salto_profundo_45cm_impulso_categoria' => 'Impulso Categoria',
                'salto_profundo_45cm_fuerza_maxima_propulsiva_categoria' => 'Fuerza Maxima Propulsiva Categoria',
                'salto_profundo_45cm_fuerza_maxima_frenado_categoria' => 'Fuerza Maxima Frenado Categoria',
                'salto_profundo_45cm_fuerza_maxima_aterrizaje_categoria' => 'Fuerza Maxima Aterrizaje Categoria',
            ],
            'Saltabilidad - Salto Profundo 60cm' => [
                'salto_profundo_60cm_rsi' => 'RSI',
                'salto_profundo_60cm_tiempo_de_piso' => 'Tiempo de Piso',
                'salto_profundo_60cm_tiempo_de_vuelo' => 'Tiempo de Vuelo',
                'salto_profundo_60cm_altura_cm' => 'Altura cm',
                'salto_profundo_60cm_impulso' => 'Impulso',
                'salto_profundo_60cm_fuerza_maxima_propulsiva' => 'Fuerza Maxima Propulsiva',
                'salto_profundo_60cm_asimetria_propulsiva_der' => 'Asimetria Propulsiva Der',
                'salto_profundo_60cm_asimetria_propulsiva_izq' => 'Asimetria Propulsiva Izq',
                'salto_profundo_60cm_fuerza_maxima_frenado' => 'Fuerza Maxima Frenado',
                'salto_profundo_60cm_asimetria_frenado_der' => 'Asimetria Frenado Der',
                'salto_profundo_60cm_asimetria_frenado_izq' => 'Asimetria Frenado Izq',
                'salto_profundo_60cm_fuerza_maxima_aterrizaje' => 'Fuerza Maxima Aterrizaje',
                'salto_profundo_60cm_asimetria_aterrizaje_der' => 'Asimetria Aterrizaje Der',
                'salto_profundo_60cm_asimetria_aterrizaje_izq' => 'Asimetria Aterrizaje Izq',
                'salto_profundo_60cm_rsi_categoria' => 'RSI Categoria',
                'salto_profundo_60cm_tiempo_de_piso_categoria' => 'Tiempo de Piso Categoria',
                'salto_profundo_60cm_altura_cm_categoria' => 'Altura cm Categoria',
                'salto_profundo_60cm_impulso_categoria' => 'Impulso Categoria',
                'salto_profundo_60cm_fuerza_maxima_propulsiva_categoria' => 'Fuerza Maxima Propulsiva Categoria',
                'salto_profundo_60cm_fuerza_maxima_frenado_categoria' => 'Fuerza Maxima Frenado Categoria',
                'salto_profundo_60cm_fuerza_maxima_aterrizaje_categoria' => 'Fuerza Maxima Aterrizaje Categoria',
            ],
            'Saltabilidad - Salto Profundo 75cm' => [
                'salto_profundo_75cm_rsi' => 'RSI',
                'salto_profundo_75cm_tiempo_de_piso' => 'Tiempo de Piso',
                'salto_profundo_75cm_tiempo_de_vuelo' => 'Tiempo de Vuelo',
                'salto_profundo_75cm_altura_cm' => 'Altura cm',
                'salto_profundo_75cm_impulso' => 'Impulso',
                'salto_profundo_75cm_fuerza_maxima_propulsiva' => 'Fuerza Maxima Propulsiva',
                'salto_profundo_75cm_asimetria_propulsiva_der' => 'Asimetria Propulsiva Der',
                'salto_profundo_75cm_asimetria_propulsiva_izq' => 'Asimetria Propulsiva Izq',
                'salto_profundo_75cm_fuerza_maxima_frenado' => 'Fuerza Maxima Frenado',
                'salto_profundo_75cm_asimetria_frenado_der' => 'Asimetria Frenado Der',
                'salto_profundo_75cm_asimetria_frenado_izq' => 'Asimetria Frenado Izq',
                'salto_profundo_75cm_fuerza_maxima_aterrizaje' => 'Fuerza Maxima Aterrizaje',
                'salto_profundo_75cm_asimetria_aterrizaje_der' => 'Asimetria Aterrizaje Der',
                'salto_profundo_75cm_asimetria_aterrizaje_izq' => 'Asimetria Aterrizaje Izq',
                'salto_profundo_75cm_rsi_categoria' => 'RSI Categoria',
                'salto_profundo_75cm_tiempo_de_piso_categoria' => 'Tiempo de Piso Categoria',
                'salto_profundo_75cm_altura_cm_categoria' => 'Altura cm Categoria',
                'salto_profundo_75cm_impulso_categoria' => 'Impulso Categoria',
                'salto_profundo_75cm_fuerza_maxima_propulsiva_categoria' => 'Fuerza Maxima Propulsiva Categoria',
                'salto_profundo_75cm_fuerza_maxima_frenado_categoria' => 'Fuerza Maxima Frenado Categoria',
                'salto_profundo_75cm_fuerza_maxima_aterrizaje_categoria' => 'Fuerza Maxima Aterrizaje Categoria',
            ],
            'Fuerza Tren Superior - Flexiones de Brazo' => [
                'flexiones_de_brazo_cantidad' => 'Cantidad',
                'flexiones_de_brazo_cantidad_promedio_por_categoria' => 'Cantidad Promedio por Categoria',
                'flexiones_de_brazo_cantidad_alta_por_categoria' => 'Cantidad Alta por Categoria',
                'flexiones_de_brazo_cantidad_baja_por_categoria' => 'Cantidad Baja por Categoria',
            ],
            'Fuerza Tren Superior - Dominadas' => [
                'dominadas_cantidad' => 'Cantidad',
                'dominadas_cantidad_promedio_por_categoria' => 'Cantidad Promedio por Categoria',
                'dominadas_cantidad_alta_por_categoria' => 'Cantidad Alta por Categoria',
                'dominadas_cantidad_baja_por_categoria' => 'Cantidad Baja por Categoria',
            ],
            'Fuerza Tren Superior - Remo Invertido' => [
                'remo_invertido_cantidad' => 'Cantidad',
                'remo_invertido_cantidad_promedio_por_categoria' => 'Cantidad Promedio por Categoria',
                'remo_invertido_cantidad_alta_por_categoria' => 'Cantidad Alta por Categoria',
                'remo_invertido_cantidad_baja_por_categoria' => 'Cantidad Baja por Categoria',
            ],
            'Fuerza Tren Superior - Lanzamiento Balon Medicinal' => [
                'lanzamiento_balon_medicinal_distancia' => 'Distancia',
                'lanzamiento_balon_medicinal_distancia_promedio_por_categoria' => 'Distancia Promedio por Categoria',
                'lanzamiento_balon_medicinal_distancia_alta_por_categoria' => 'Distancia Alta por Categoria',
                'lanzamiento_balon_medicinal_distancia_baja_por_categoria' => 'Distancia Baja por Categoria',
            ],
            'Perfil Muscular Tren Inferior - Carga 1' => [
                'carga_1_peso' => 'Peso',
                'carga_1_m_s' => 'm/s',
                'carga_1_potencia' => 'Potencia',
            ],
            'Perfil Muscular Tren Inferior - Carga 2' => [
                'carga_2_peso' => 'Peso',
                'carga_2_m_s' => 'm/s',
                'carga_2_potencia' => 'Potencia',
            ],
            'Perfil Muscular Tren Inferior - Carga 3' => [
                'carga_3_peso' => 'Peso',
                'carga_3_m_s' => 'm/s',
                'carga_3_potencia' => 'Potencia',
            ],
            'Perfil Muscular Tren Inferior - Carga 4' => [
                'carga_4_peso' => 'Peso',
                'carga_4_m_s' => 'm/s',
                'carga_4_potencia' => 'Potencia',
            ],
            'Perfil Muscular Tren Inferior - Carga 5' => [
                'carga_5_peso' => 'Peso',
                'carga_5_m_s' => 'm/s',
                'carga_5_potencia' => 'Potencia',
            ],
            'Perfil Muscular Tren Inferior - Carga 6' => [
                'carga_6_peso' => 'Peso',
                'carga_6_m_s' => 'm/s',
                'carga_6_potencia' => 'Potencia',
            ],
            'Perfil Muscular Tren Inferior - Fuerza Maxima' => [
                'fuerza_maxima' => 'Fuerza Maxima',
                'fuerza_maxima_promedio_categoria' => 'Fuerza Maxima Promedio Categoria',
                'fuerza_maxima_promedio_alta' => 'Fuerza Maxima Promedio Alta',
                'fuerza_maxima_promedio_baja' => 'Fuerza Maxima Promedio Baja',
            ],
            'IMTP' => [
                'imtp_fuerza_maxima' => 'Fuerza Maxima',
                'imtp_rfd_250ms' => 'RFD 250ms',
                'imtp_fuerza_relativa_al_peso_corporal' => 'Fuerza Relativa (al Peso Corporal)',
            ],
            'Indice Fuerza Dinamica' => [
                'indice_fuerza_dinamica' => 'Indice Fuerza Dinamica',
            ],
            'Velocidad - 5m' => [
                '5m_tiempo' => '5m tiempo',
                '5m_km_h' => '5m km/h',
                '5m_m_s' => '5m m/s',
                '5m_tiempo_promedio' => '5m tiempo Promedio',
                '5m_km_h_promedio' => '5m km/h Promedio',
                '5m_m_s_promedio' => '5m m/s Promedio',
                '5m_tiempo_alto' => '5m tiempo Alto',
                '5m_km_h_alto' => '5m km/h Alto',
                '5m_m_s_alto' => '5m m/s Alto',
                '5m_tiempo_bajo' => '5m tiempo Bajo',
                '5m_km_h_bajo' => '5m km/h Bajo',
                '5m_m_s_bajo' => '5m m/s Bajo',
            ],
            'Velocidad - 10m' => [
                '10m_tiempo' => '10m tiempo',
                '10m_km_h' => '10m km/h',
                '10m_m_s' => '10m m/s',
                '10m_tiempo_promedio' => '10m tiempo Promedio',
                '10m_km_h_promedio' => '10m km/h Promedio',
                '10m_m_s_promedio' => '10m m/s Promedio',
                '10m_tiempo_alto' => '10m tiempo Alto',
                '10m_km_h_alto' => '10m km/h Alto',
                '10m_m_s_alto' => '10m m/s Alto',
                '10m_tiempo_bajo' => '10m tiempo Bajo',
                '10m_km_h_bajo' => '10m km/h Bajo',
                '10m_m_s_bajo' => '10m m/s Bajo',
            ],
            'Velocidad - 15m' => [
                '15m_tiempo' => '15m tiempo',
                '15m_km_h' => '15m km/h',
                '15m_m_s' => '15m m/s',
                '15m_tiempo_promedio' => '15m tiempo Promedio',
                '15m_km_h_promedio' => '15m km/h Promedio',
                '15m_m_s_promedio' => '15m m/s Promedio',
                '15m_tiempo_alto' => '15m tiempo Alto',
                '15m_km_h_alto' => '15m km/h Alto',
                '15m_m_s_alto' => '15m m/s Alto',
                '15m_tiempo_bajo' => '15m tiempo Bajo',
                '15m_km_h_bajo' => '15m km/h Bajo',
                '15m_m_s_bajo' => '15m m/s Bajo',
            ],
            'Velocidad - 20m' => [
                '20m_tiempo' => '20m tiempo',
                '20m_km_h' => '20m km/h',
                '20m_m_s' => '20m m/s',
                '20m_tiempo_promedio' => '20m tiempo Promedio',
                '20m_km_h_promedio' => '20m km/h Promedio',
                '20m_m_s_promedio' => '20m m/s Promedio',
                '20m_tiempo_alto' => '20m tiempo Alto',
                '20m_km_h_alto' => '20m km/h Alto',
                '20m_m_s_alto' => '20m m/s Alto',
                '20m_tiempo_bajo' => '20m tiempo Bajo',
                '20m_km_h_bajo' => '20m km/h Bajo',
                '20m_m_s_bajo' => '20m m/s Bajo',
            ],
            'Velocidad - 25m' => [
                '25m_tiempo' => '25m tiempo',
                '25m_km_h' => '25m km/h',
                '25m_m_s' => '25m m/s',
                '25m_tiempo_promedio' => '25m tiempo Promedio',
                '25m_km_h_promedio' => '25m km/h Promedio',
                '25m_m_s_promedio' => '25m m/s Promedio',
                '25m_tiempo_alto' => '25m tiempo Alto',
                '25m_km_h_alto' => '25m km/h Alto',
                '25m_m_s_alto' => '25m m/s Alto',
                '25m_tiempo_bajo' => '25m tiempo Bajo',
                '25m_km_h_bajo' => '25m km/h Bajo',
                '25m_m_s_bajo' => '25m m/s Bajo',
            ],
            'Velocidad - 30m' => [
                '30m_tiempo' => '30m tiempo',
                '30m_km_h' => '30m km/h',
                '30m_m_s' => '30m m/s',
                '30m_tiempo_promedio' => '30m tiempo Promedio',
                '30m_km_h_promedio' => '30m km/h Promedio',
                '30m_m_s_promedio' => '30m m/s Promedio',
                '30m_tiempo_alto' => '30m tiempo Alto',
                '30m_km_h_alto' => '30m km/h Alto',
                '30m_m_s_alto' => '30m m/s Alto',
                '30m_tiempo_bajo' => '30m tiempo Bajo',
                '30m_km_h_bajo' => '30m km/h Bajo',
                '30m_m_s_bajo' => '30m m/s Bajo',
            ],
            'Agilidad' => [
                '5_x_2_der_tiempo' => '5 x 2 Der Tiempo',
                '5_x_2_der_tiempo_promedio_categoria' => '5 x 2 Der Tiempo Promedio Categoria',
                '5_x_2_der_tiempo_alto_categoria' => '5 x 2 Der Tiempo Alto Categoria',
                '5_x_2_der_tiempo_bajo_categoria' => '5 x 2 Der Tiempo Bajo Categoria',
                '5_x_2_izq_tiempo' => '5 x 2 Izq Tiempo',
                '5_x_2_izq_tiempo_promedio_categoria' => '5 x 2 Izq Tiempo Promedio Categoria',
                '5_x_2_izq_tiempo_alto_categoria' => '5 x 2 Izq Tiempo Alto Categoria',
                '5_x_2_izq_tiempo_bajo_categoria' => '5 x 2 Izq Tiempo Bajo Categoria',
                'defict_cambio_de_direccion_der' => 'Defict Cambio de Direccion Der',
                'defict_cambio_de_direccion_izq' => 'Defict Cambio de Direccion Izq',
            ],
            'Resistencia' => [
                'nivel' => 'Nivel',
                'nivel_promedio_categoria' => 'Nivel Promedio Categoria',
                'nivel_alto_categoria' => 'Nivel Alto Categoria',
                'nivel_bajo_categoria' => 'Nivel Bajo Categoria',
                'vam' => 'VAM',
                'vam_promedio_categoria' => 'VAM Promedio Categoria',
                'vam_alto_categoria' => 'VAM Alto Categoria',
                'vam_bajo_categoria' => 'VAM Bajo Categoria',
                'vo2max' => 'Vo2Max',
                'vo2max_promedio_categoria' => 'Vo2Max Promedio Categoria',
                'vo2max_alto_categoria' => 'Vo2Max Alto Categoria',
                'vo2max_bajo_categoria' => 'Vo2Max Bajo Categoria',
            ],
            'Indice Total de Atleticismo' => [
                'indice_total_de_atleticismo' => 'Indice Total de Atleticismo',
            ],
            'Deteccion de Talento - Deportes Colectivo' => [
                'futbol' => 'Futbol',
                'basket' => 'Basket',
                'volley' => 'Volley',
                'handball' => 'Handball',
            ],
            'Deteccion de Talento - Deportes Individuales' => [
                'tenis' => 'Tenis',
                'golf' => 'Golf',
                'atletismo' => 'Atletismo',
                'natacion' => 'Natacion',
                'judo' => 'Judo',
                'lucha_olimpica' => 'Lucha Olimpica',
                'taekwondo' => 'Taekwondo',
                'karate' => 'Karate',
            ],
            'MOBAK' => [
                'lanzar' => 'Lanzar',
                'atrapar' => 'Atrapar',
                'conduccion_manos' => 'Conduccion (Manos)',
                'conduccion_pies' => 'Conduccion (Pies)',
                'equilibrarse' => 'Equilibrarse',
                'rodar' => 'Rodar',
                'saltar' => 'Saltar',
                'correr' => 'Correr',
            ],
        ];
    }
}